export const USER_LOGIN="USER_LOGIN";
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_STATUS = {
    "PENDING" : 0,
    "ACCEPTED" : 1,
    "REJECTED" : 2,
    "UNSUBSCRIBED" : 3,
}
export const CHANGE_PASSWORD="CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CLOSE_CHANGE_PASS_MODAL = "CLOSE_CHANGE_PASS_MODAL";
export const RESET_PASSWORD_EMAIL_SENT = "RESET_PASSWORD_EMAIL_SENT";
export const RESET_PASSWORD_EMAIL_SENT_SUCCESS = "RESET_PASSWORD_EMAIL_SENT_SUCCESS";
export const RESET_PASSWORD_EMAIL_SENT_FAIL = "RESET_PASSWORD_EMAIL_SENT_FAIL";
export const RESET_PASSWORD_EMAIL_TOKEN_SENT = "RESET_PASSWORD_EMAIL_TOKEN_SENT";
export const RESET_PASSWORD_EMAIL_TOKEN_SENT_SUCCESS = "RESET_PASSWORD_EMAIL_TOKEN_SENT_SUCCESS";
export const RESET_PASSWORD_EMAIL_TOKEN_SENT_FAIL = "RESET_PASSWORD_EMAIL_TOKEN_SENT_FAIL";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";