export const GET_VEHICLE_HISTORY="GET_VEHICLE_HISTORY";
export const GET_VEHICLE_HISTORY_SUCCESS="GET_VEHICLE_HISTORY_SUCCESS";
export const GET_VEHICLE_HISTORY_FAIL = "GET_VEHICLE_HISTORY_FAIL";
export const GET_VEHICLE_RECOMMENDATION="GET_VEHICLE_RECOMMENDATION";
export const GET_VEHICLE_RECOMMENDATION_SUCCESS="GET_VEHICLE_RECOMMENDATION_SUCCESS";
export const GET_VEHICLE_RECOMMENDATION_FAIL = "GET_VEHICLE_RECOMMENDATION_FAIL";